devices:
   - { host: R1, transport: http, username: admin, password: admin, enable_password: admin, port: 80 }
   - { host: R2, transport: http, username: admin, password: admin, enable_password: admin, port: 80 }
commands:
   - {command: "show version", interval: 10}
   - {command: "show ip interface brief", interval: 30}
   - {command: "show vlan", interval: 30}
   - {command: "show ip bgp summary", interval: 5}
   - {command: "show ntp associations", interval: 30}
   - {command: "show clock", interval: 60}
